### PR TITLE
A few build fixes

### PR DESCRIPTION
**Pull request by simonbyrne**
- Fix library extension
- remove deprecated syntax
- don't rely on `Pkg.dir`

Also I've updated .travis to match REQUIRE (these should probably be consistent)

### CODE REVIEW

**Comment by simonster** [comment]
Thanks!

**Comment by simonbyrne** [comment]
Wow, I'm impressed 0.3 still works!

**Comment by simonbyrne** [comment]
I think I'm done for now. Any chance you could tag a new version?

**Comment by simonster** [comment]
Yeah, I guess we need to drop 0.3 support so that I'm allowed to submit to METADATA.

**Pull request merged**
